### ISSUE TITLE
make install 

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#188]
I closed a previous issue about make install found when converting pwmig code.   This is a new issue.

I think make install is currently completely broken.   It is now trying to install libmspass.a in /usr/local/lib and the include files in /usr/local/include.   This happens when I know MSPASS_HOME is set.  I presume something got changed in the cmake configurations that I am not able to find.  I'm hoping you can find it more easily than I.   Not a huge issue as I can do the same things easily manually, but it is a minor blemish at this point.  I reiterate it is not a high priority as there is a simple workaround and I'm the only person affected at this point and likely for a long time.

**Comment by wangyinz** [comment]
By broken do you mean that it cannot install the files to a custom location? Did you correctly set the [CMAKE_INSTALL_PREFIX](https://cmake.org/cmake/help/latest/variable/CMAKE_INSTALL_PREFIX.html) (i.e., adding `-DCMAKE_INSTALL_PREFIX=/path/to/install/dir` to your cmake command)? You can also use the `DESTDIR` in the make command.

**Comment by pavlis** [comment]
I guess broken was the wrong word then.  It just changed sometime in the past couple months.  Previously when I did make install results were defaulted to $MSPASS_HOME.   

I was no aware of either of those options.   When I've had time to verify this I'll try to update the wiki page related to this point.

**Comment by wangyinz** [comment]
hmmm... that is weird. I don't think I have ever implemented anything in our CMake setup to interpret the `MSPASS_HOME` environment variable. It should never install any of the lib or headers there. 

I guess we do have a problem here regarding that `MSPASS_HOME` variable, which is that it will throw an exception when not defined. i.e.:

https://github.com/wangyinz/mspass/blob/cc10c4d7d720c67cb9d250d8dbbf27648487e78b/cxx/src/lib/utility/data_directory.cc#L7-L13

This function is called [here](https://github.com/wangyinz/mspass/blob/cc10c4d7d720c67cb9d250d8dbbf27648487e78b/cxx/src/lib/utility/AttributeMap.cc#L204) and [here](https://github.com/wangyinz/mspass/blob/cc10c4d7d720c67cb9d250d8dbbf27648487e78b/cxx/src/lib/utility/MetadataDefinitions.cc#L35) (the latter should probably be removed completely).  Also, I found that our C++ code has another similar env var dependency: 

https://github.com/wangyinz/mspass/blob/d5899ab67daff8f81887bb75b9d2e14f0e76a327/cxx/src/lib/utility/AntelopePf.cc#L371-L372

In the Python code, we also have the `MSPASS_HOME` dependency, but it is implemented in a way that it will never throw an exception: 

https://github.com/wangyinz/mspass/blob/c0c0a376c351b28c64994a7c40aaf351f9e82302/python/mspasspy/db/schema.py#L16-L25

I think we should do something similar in the C++ code, where we default the directory to where mspass is installed or just the current directory. The latter is simple but can still easily lead to the exception, and I am not quite sure how to achieve the former in C++ (i.e., get the location of the library at runtime). Any thoughts? If we can do that, we should also add the `data` directory to the cmake installation.

**Comment by pavlis** [comment]
Well, it is not impossible I had something odd set when make install behaved as I described so let's just dismiss that as something in the past we can't recreate.  Your points, however, do need to be addressed.  I remember a long time ago discussing the need for MsPASS_HOME and that is no doubt when the code above was produced.  

It does make sense to have a default for MsPASS_HOME.  The python you used does not translate.   I would suggest we use the current directory (standard C function getcwd) as the default.  

The PFFILE in AntelopePf is a bug.  The equivalent of PFFILE should resolve to $MSPASS_HOME/data/pf.  The data directory already has some pf files used by some C functions.

**Comment by pavlis** [comment]
This problem with MSPASS_HOME cropped up again and I'm not sure what has happened.   I was trying to rebuilt local libraries (static .a libraries that is and local include files) for building the new plane wave migration code using mspass.   I have the most recent master branch.  I even removed my build directory and built everything from scratch in build (cmake ..; make).   The problem is that when I run "make install" I get this:
```
-- Installing: /usr/local/lib/libmspass.a
CMake Error at src/lib/cmake_install.cmake:46 (file):
  file INSTALL cannot copy file
  "/home/pavlis/src/mspass/cxx/build/src/lib/libmspass.a" to
  "/usr/local/lib/libmspass.a": Permission denied.
Call Stack (most recent call first):
  src/cmake_install.cmake:47 (include)
  cmake_install.cmake:48 (include)
```
Noting I do have MSPASS_HOME set to something else:
```
(base) pavlis@pavlis-linux:~/src/mspass/cxx/build$ echo $MSPASS_HOME
/home/pavlis/mspass
```
I don't see any reference to MSPASS_HOME in the cmake configuration files.   Did this get "fixed" for something else that broke make install?   I'm not proficient enough at following the change history to know and I'm not even sure what I'm looking for.   How can we address this?

**Comment by wangyinz** [comment]
Well, this is never a problem. As I said above, `MSPASS_HOME` was never used to specify the install directory of the package. To specify the install directory with cmake, you need something like `cmake .. -DCMAKE_INSTALL_PREFIX=/path/to/install/dir` and then `make install`. Otherwise, the default install dir will be under the `/user/local`. `MSPASS_HOME` is only used to tell MsPASS where to find the default parameter files.

**Comment by pavlis** [comment]
My bad for not reading the previous discussion of this topic more carefully.  I can't believe I missed point to the MAKE_INSTALL_PREFIX in that way.   I fell into the all to common problem in the internet reading world of skimming and missing what I was looking for. 

I do think i will edit the wiki entry on compiling MsPASS from source code to discuss this issue.  It could arise easily if someone where trying to build a local copy on an cluster for which they didn't have root access but still wanted to build the C libraries.   Not a common need, I suspect, but probably worth putting in the wiki page.

**Comment by pavlis** [comment]
Turned out there was some mention of this in the wiki page, but I extended it to make the need clearer (I hope).  

You may want to close this issue.
