### ISSUE TITLE
Ubuntu build warnings - DEPRECATION message

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#249]
I've been getting this warning for a while when I build mspass on my ubuntu machine:
```
(base) pavlis@pavlis-linux:~/src/mspass$ pip install --user ./
WARNING: Ignoring invalid distribution -spasspy (/home/pavlis/.local/lib/python3.8/site-packages)
WARNING: Ignoring invalid distribution -spasspy (/home/pavlis/.local/lib/python3.8/site-packages)
Processing /home/pavlis/src/mspass
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
Requirement already satisfied: pyyaml in /home/pavlis/anacond
```
I think the first few lines are something wrong in my local copy.  Don't think they are relevant but put them there in case they are. 

The issue is the DEPRECATION warning.   Do we need to deal with that now instead of waiting for it to break with a future python release?

**Comment by wangyinz** [comment]
I tested and found that the change has no impact to us, and this seems to be the norm based on the discussion [here](https://github.com/pypa/pip/issues/7555).
