### ISSUE TITLE
bug in read_data

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#262]
I have discovered a clear bug in the read_data method of Database.   The bug is failure to properly handle an error in specifying a normalize collection.    The bug was uncovered by my a dumb mistake I made while using the reader where I remembered a name wrong.  That is I used `normalize=['event','site']` instead of the mspass schema correct call `normalize=['source','site']`.   

I don't know how you do the links to github to a highlight a code segment, so I'll just paste  in the problem code.  This is lines 334-350 of database.py:

```
        # 1.2 read the attributes in the metadata schema
        col_dict = {}
        for k in read_metadata_schema.keys():
            col = read_metadata_schema.collection(k)
            # 1.2.1. col is not None and is a normalized collection name
            # 1.2.2. normalized key id exists in the wf document
            # 1.2.3. k is not one of the exclude keys
            # 1.2.4. col is in the normalize list provided by user
            if col and col != wf_collection and col+'_id' in object_doc and k not in exclude_keys and col in normalize:
                if col not in col_dict:
                    col_dict[col] = self[col].find_one(
                        {'_id': object_doc[col + '_id']})
                # might unable to find the normalized document by the normalized_id in the object_doc
                # TODO: this is not covered by test
                if not col_dict[col]:
                    continue
                md[k] = col_dict[col][self.database_schema[col].unique_name(k)]
```
That throws this error that is not at all descriptive of the true problem:
```

  File "/home/pavlis/data/copy_pwmigtest/runpwstack.py", line 18, in <module>
    pwstack_return = pwstack(db,pf,slowness_grid_tag='Slowness_Grid_Definition')

  File "/home/pavlis/.local/lib/python3.8/site-packages/pwmigpy/pwmig/pwstack.py", line 398, in pwstack
    d=read_ensembles(db,q,control)

  File "/home/pavlis/.local/lib/python3.8/site-packages/pwmigpy/pwmig/pwstack.py", line 274, in read_ensembles
    d=db.read_ensemble_data(cursor,collection='wf_Seismogram',

  File "/home/pavlis/.local/lib/python3.8/site-packages/mspasspy/db/database.py", line 2244, in read_ensemble_data
    data = self.read_data(i, mode=mode, normalize=normalize, load_history=load_history, exclude_keys=exclude_keys, collection=wf_collection,

  File "/home/pavlis/.local/lib/python3.8/site-packages/mspasspy/db/database.py", line 350, in read_data
    md[k] = col_dict[col][self.database_schema[col].unique_name(k)]

KeyError: 'net'
```
The TODO comment in the code is right on target because that is indeed the section that has the problem.  

I would try to fix this, but I am afraid I'm not totally sure what all that code section is doing.   Besides fixing this bug I suggest whoever gets the job of doing the fix add some additional comments on what each code segment in the read_data method is doing.   

What is needed is fairly clear, but how to do so is not something I want to try as the complexity here could create unintended side effects created by my incomplete understanding of this code.  That is, what is needed is to just trap the error condition I made early in the read code:  an undefined normalize collection.    It should be assumed that collection listed as one to use for normalization should be defined in the schema.  It seems fair to abort if one tries to use an undefined collection as I did.

**Comment by wangyinz** [comment]
@haruming Could you please address this? Seems to be an easy fix.

**Comment by haruming** [comment]
Sure, I will look into it soon!

**Comment by pavlis** [comment]
Sorry, but there seems to be more to this problem.  Note in all those words above the error thrown was a KeyError exception on the attribute with the key "net".   I think there is a bigger bug in that section related to handling of whether or not an attribute is "normal" (or other similar) versus "required".  The problem I'm seeing is that when the reader is run on data I'm trying to load this code segment is doing something wrong.    Here is my debug version I tried with print statements needed to understand the output I'll show after:
```
        # 1.2 read the attributes in the metadata schema
        col_dict = {}
        for k in read_metadata_schema.keys():
            col = read_metadata_schema.collection(k)
            # debug
            print(k,col)
            # 1.2.1. col is not None and is a normalized collection name
            # 1.2.2. normalized key id exists in the wf document
            # 1.2.3. k is not one of the exclude keys
            # 1.2.4. col is in the normalize list provided by user
            if col and col != wf_collection and col+'_id' in object_doc and k not in exclude_keys and col in normalize:
                if col not in col_dict:
                    col_dict[col] = self[col].find_one(
                        {'_id': object_doc[col + '_id']})
                # might unable to find the normalized document by the normalized_id in the object_doc
                # TODO: this is not covered by test
                if not col_dict[col]:
                    continue

                md[k] = col_dict[col][self.database_schema[col].unique_name(k)]
                # debug
                print('metadata set=',k,md[k])
```
The print statements when this was run are these leading up to the KeyError exception being thrown at line 350:
```
_id wf_Seismogram
npts wf_Seismogram
delta wf_Seismogram
sampling_rate wf_Seismogram
starttime wf_Seismogram
time_standard wf_Seismogram
calib wf_Seismogram
site_id wf_Seismogram
source_id wf_Seismogram
tmatrix wf_Seismogram
net site
```
The if conditional block is not entered at all until the "net site" pair is tested.   On  line 350 `[self.database_schema[col].unique_name(k)]` correctly resolves to 'net'.   The problem is this:
```
IPdb [4]: col_dict[col]
{'_id': ObjectId('617d4c2766d6360656038e87'), 'lat': 36.389, 'lon': -121.552, 'elev': 0.542, 'coordinates': [-121.552, 36.389], 'sta': 'HAST'}
```
which shows this problem is being created by an issue with this data set that conflicts with the code is trying to do.  My "site" collection for this test data set does not define "net" or "loc".  Both are listed in the schema as "normal", but this section is treating them like they are required.   

I think there may also be a build in  inefficiency in this code section whose solution might be a solution to this bug.  I wonder if that loop should not be driven by what actually is in col_dict instead of looping through the keys defined in the schema.   The alternative fix is to bypass the problem code if a key is not required.  I'm not sure which is right that would not produce unintended consequences.  I think I understand this code a bit better right now but it is still a bit mysterious.  

To be clear - the original bug point remains an issue.  This just shows there is a second bug hidden in the same code block and the error was mysterious because my guess about the case (using 'event' instead of 'source') was not the actual problem. I reiterate the original remains an issue also.

**Comment by wangyinz** [comment]
Aha, this is clearly a bug. A missing "normal" key should be captured and logged in the elog here. I guess part of the problem is that in our design doc, we did not define the behavior for missing keys. The constraints such as required, normal, and optional are designed for mismatching types only. We did not consider this scenario where the key definitions are mismatched between the schema and database. Part of it is that we expect the user to change the schema when needed. However, such an error is inacceptable anyway.

**Comment by haruming** [comment]
That's a clear bug and I didn't find that earlier, thanks for pointing it out!
I think we better ignore reading the attributes if they are not in the normalized records. However, if they are required attributes, we should post an elog entry to the wf object created after.

**Comment by pavlis** [comment]
I agree.   Incidentally this bug will cause any read to fail with normalization if any attribute listed in the schema is not defined in the document linked with the id (the normalizing document from a collection like site and source.)   I know this because I had to do a workaround for source as well as site until this is fixed.
