### ISSUE TITLE
pybind11 ErrorLogger.log_error TypeError with MsPASSError argument

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#277]
I uncovered a subtle error that I think is created by pybind11 and the way we implemented the MsPASSError C++ class as a python exception.   

This block of code is failing 
```
try:
   # many lines here, several of which could throw a MsPASSError exception
except MsPASSError as err:
        data_object.elog.log_error(err)
```
When the handler section above is entered (something threw a MsPASSError) I get this:
```
raceback (most recent call last):

  File "/home/pavlis/.local/lib/python3.8/site-packages/mspasspy/algorithms/snr.py", line 385, in FD_snr_estimator
    stats = BandwidthStatistics(S,N,bwd)

MsPASSError: VectorStatistics constructor:  input vector has insufficient data to compute statistics


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/pavlis/tmp/testsnr.py", line 32, in <module>
    d=arrival_snr_QC(d,taup_model=ttmodel)

  File "/home/pavlis/.local/lib/python3.8/site-packages/mspasspy/algorithms/snr.py", line 685, in arrival_snr_QC
    snrdata=FD_snr_estimator(data_to_process,noise_window,noise_spectrum_engine,

  File "/home/pavlis/.local/lib/python3.8/site-packages/mspasspy/algorithms/snr.py", line 421, in FD_snr_estimator
    data_object.elog.log_error(err)

TypeError: log_error(): incompatible function arguments. The following argument types are supported:
    1. (self: mspasspy.ccore.utility.ErrorLogger, arg0: mspass::utility::MsPASSError) -> int
    2. (self: mspasspy.ccore.utility.ErrorLogger, arg0: str, arg1: str, arg2: mspasspy.ccore.utility.ErrorSeverity) -> int

Invoked with: <mspasspy.ccore.utility.ErrorLogger object at 0x7fa7264e0430>, MsPASSError('VectorStatistics constructor:  input vector has insufficient data to compute statistics', <ErrorSeverity.Invalid: 1>)
```
A lot there but the key thing is this line:
```
TypeError: log_error(): incompatible function arguments. The following argument types are supported:
    1. (self: mspasspy.ccore.utility.ErrorLogger, arg0: mspass::utility::MsPASSError) -> int
    2. (self: mspasspy.ccore.utility.ErrorLogger, arg0: str, arg1: str, arg2: mspasspy.ccore.utility.ErrorSeverity) -> int
```
In a debugger I find this:
```
IPdb [4]: type(err)
<class 'mspasspy.ccore.utility.MsPASSError'>
```

SOOO this error is caused by the fact that err is a `mspasspy.ccore.utility.MsPASSError` but the binding code defines the arg0 for the overloaded function called `log_error` as a `mspass::utility::MsPASSError`.  the first is a python name and the second is a C++ name. 

The pybind11 code that defines this overload is the following:
```
   .def("log_error",py::overload_cast<const MsPASSError&>(&ErrorLogger::log_error),"log error thrown as MsPASSError")
    .def("log_error",py::overload_cast<const std::string,const std::string,const ErrorSeverity>(&ErrorLogger::log_error),"log a message at a specified severity level")
```
I can't find anything in the pybind11 code in cxx/python/utility that could easily explain why the symbol for MsPASSError is incorrectly translated to C++ namespace syntax. 

There is an easy workaround I'll use for now.  The MsPASSError is caught so I can just extract the message string in the handler like this:
```
except MsPASSError as err:
  data_object.elog.log_error("thisalgorithname",err.message,err.severity)
```
I put this out here on github because it may take a while for us to solve this as this error is likely deep in the weeds of pybind11.  I searched the python code base as below and found this error is a set of bugs waiting to happen:
```
(base) pavlis@pavlis-linux:~/src/mspass/python/mspasspy$ grep "except MsPASSError" *.py */*.py
algorithms/RFdeconProcessor.py:    except MsPASSError as err:
algorithms/RFdeconProcessor.py:    except MsPASSError as err:
algorithms/snr.py:    except MsPASSError as err:
algorithms/window.py:    except MsPASSError as err:
algorithms/window.py:    except MsPASSError as err:
db/database.py:        except MsPASSError as err:
db/database.py:        except MsPASSError as err:
util/decorators.py:    except MsPASSError as ex:
util/decorators.py:    except MsPASSError as ex:
util/decorators.py:    except MsPASSError as ex:
util/seispp.py:            except MsPASSError:
```
If we can't find a fix the pybind11 problem we will need to apply this workaround to all the hits above.  

I'm punting this to you, @wangyinz, because I suspect strongly this problem is the the code you created to define MsPASSError as a valid python exception instead of pybind11's default mapping to RuntimeError - something you did quite a while ago.

**Comment by wangyinz** [comment]
OK, I think I know what the problem is. Basically, the line below is a relic from the old implementation.
https://github.com/mspass-team/mspass/blob/b18f40f46c3134fcc782df84423605abfd15e5ea/cxx/python/utility/utility_py.cc#L724
The C++ object `mspass::utility::MsPASSError` is no longer bind to Python in the new implementation, so to pybind11, this object type does not exist. To fix this issue, all we need to do is to implement a new `log_error` method that can handle the Python object `mspasspy.ccore.utility.MsPASSError`, and it requires writing the Python code in C++ with the pybind11 library. This is obviously not as straightforward as it sounds. I will try to fix it when I got the chance to focus on it.
