### ISSUE TITLE
docker problem with jupyter notebooks on arm mac running big sur

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#306]
I tried running our current mspass container on my mac mini which has an arm processor (i.e. != intel) running "big sur".   I immediately warns me with this message when I do our standard docker run command to launch a notebook:
```
base) pavlis@PavlisHome G690work % docker run -p 8888:8888 --mount src=`pwd`,target=/home,type=bind mspass/mspass
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
[I 14:01:08.851 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 14:01:09.889 NotebookApp] Serving notebooks from local directory: /
[I 14:01:09.890 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 14:01:09.890 NotebookApp] http://f6f4ec6491d2:8888/?token=98ed067b6fbcf2ea4ac53fea7b4aacf027ac432e6fa5b4b8
[I 14:01:09.891 NotebookApp]  or http://127.0.0.1:8888/?token=98ed067b6fbcf2ea4ac53fea7b4aacf027ac432e6fa5b4b8
[I 14:01:09.891 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:01:09.912 NotebookApp] 
```
As soon as I try to create a notebook in a web browser this happens:
```
[I 14:08:07.718 NotebookApp] Creating new notebook in /home
[I 14:08:07.751 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 14:08:09.953 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20220307140724 (172.17.0.1) 45.720000ms referer=http://127.0.0.1:8888/notebooks/home/Untitled.ipynb?kernel_name=python3
Operation not permitted (src/thread.cpp:309)
qemu: uncaught target signal 6 (Aborted) - core dumped
/usr/sbin/start-mspass.sh: line 30:    55 Aborted                 jupyter notebook ${NOTEBOOK_ARGS}
```
This does not, however, seem to be an intrinsic problem with python or the container but something that is colliding with notebook use on this type of hardware or this software version.   i.e. it looks like the notebook server is dying and taking down the whole run with it.   I say this as I can launch it this way and can run python normally from bash:
```
docker run -it --mount src=`pwd`,target=/home,type=bind mspass/mspass bash
```
This may be a symptom of a similar problem @wangyinz  and I have been trying to resolve for a couple weeks with a notebook that dies mysteriously while trying to run the latest prototype preprocessing job for a year of USArray data.   How can we sort this problem out to resolve it?

**Comment by wangyinz** [comment]
As discussed internally, arm support is not a priority atm.
