### ISSUE TITLE
Wrong use of GIL in pybind11 may cause segmentation fault

### ISSUE THREAD

**Issue by wangyinz** [mspass-team/mspass#355]
In https://github.com/mspass-team/mspass/commit/985ac83d342f2074634e6ce19b2fe224deca6cbc, I fixed a bug in the use of GIL release in pybind11. The bug has been there for quite a while now, but it never showed up as a problem until I switched our GitHub Action to include Python 3.10 under Ubuntu 22.04. In this build, the `test_ccore.py` will throw a segmentation fault like following:
```
......
Fatal Python error: Segmentation fault

Current thread 0x00007f25ddbf4c40 (most recent call first):
  File "/home/runner/work/mspass/mspass/python/tests/test_ccore.py", line 870 in test_Ensemble
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/_pytest/python.py", line [19](https://github.com/mspass-team/mspass/actions/runs/3609683811/jobs/6083024842#step:11:20)5 in pytest_pyfunc_call
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/opt/hostedtoolcache/Python/3.10.8/x64/lib/python3.10/site-packages/pluggy/_hooks.py", line 265 in __call__
......
```
which is at this line that tests for pickle:
https://github.com/mspass-team/mspass/blob/985ac83d342f2074634e6ce19b2fe224deca6cbc/python/tests/test_ccore.py#L870

I Googled a bit and found that the issue is like the one described in https://github.com/pybind/pybind11/issues/4015. I then realized that we released GIL before creating the tuple with pybind11. This is obviously not allowed (more details [here](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil)). So, I got it quickly fixed in the commit referenced at the beginning, but I think it worth preserving a record here on a mysterious error like this. Of course, the reason why it never errored out in our previous build of Python 3.6 and 3.8 remains a mystery.

**Comment by pavlis** [comment]
Have you checked for other mistakes like this in the pybind11 code in the pickle sections?   That kind of thing tends to be carried around as an incantation that has be be chanted at the right moment so other pickle sections could share this error.

**Comment by wangyinz** [comment]
Yes, I have checked all explicit uses of `gil_scoped_release`, and they should all be fine. Also, this is another reason why we need a good test coverage - I wouldn't have noticed it without our tests. 

By carefully reading the GIL related sessions, it appears to me that we might got it fundamentally wrong on the GIL behavior of pybind11. According to the documentation, it says "As a result, when Python calls into C++ via pybind11 the GIL must be held, and pybind11 will never implicitly release the GIL". It seems this is suggesting that all of our C++ code are locked into a single thread. The GIL will only be released if the C++ code is bond like this: 
```
m.def("call_go", &call_go, py::call_guard<py::gil_scoped_release>());
```
which uses the `call_guard` to release the GIL explicitly. In our code, however, we are doing the opposite assuming the GIL is always released, and we explicitly acquire the GIL when Python objects is used in the C++ code. If that is the case, I think it makes sense why the OpenMP implementation you had did not run on multiple threads.

**Comment by Aristoeu** [comment]
I tested OpenMP and pybind11 using the following code:
```
int tests_for_openmp(){
    double x = 0, y = 0;
	int m = 50000000;
	#pragma omp parallel for reduction(+:x,y)
    for(int i = 1; i < m; i++)
    {
       double rand_g1 = cos(i/double(m));
	   double rand_g2 = sin(i/double(m));

	   x += rand_g1;
       y += rand_g2;
    }
	return 0;
}
```
When I added `#pragma omp parallel for reduction(+:x,y)` and ran it in Python, it used half-time. So I think it works here and does not need to add `gil_scoped_release` in the bond code. I used the following bond code:
```
  m.def("_tests_for_openmp", &tests_for_openmp, "tests for openmp",  py::return_value_policy::copy);
```

There may be other reasons OpenMP does not work. For example, not adding "-fopenmp" in cmakelists.txt, or not using the reduction clause.

In addition to pybind11, there is also a simpler way using openmp in Python:
[pyMP](https://github.com/classner/pymp), a package that brings OpenMP-like functionality to Python. The GIL (global interpreter lock) is circumvented by using the operating system's fork method. I tested it locally, and it works well. It does not need pybind 11 or gil_scoped_release, but requires some code changes to use the package.
```
import pymp
ex_array = pymp.shared.array((100,), dtype='uint8')
with pymp.Parallel(4) as p: # 4 threads
    for index in p.range(0, 100):
        ex_array[index] = 1
        # The parallel print function takes care of asynchronous output.
        p.print('Yay! {} done!'.format(index))
```

**Comment by wangyinz** [comment]
Cool! Thanks for looking into that! It is a bit surprising that the behavior of pybind11 does not conform with its documentation (or it could be that I read it wrong). Since OpenMP works as expected in your example, we will need to investigate why it doesn't work for pwmig. But that's outside of the scope of this issue, so I will close it now.

For the pyMP, it is an interesting package, but I don't think it is very helpful to us in pwmig as that is mainly a C++ code. Also, the package does not seem very mature, so it may not worth the investment at the moment. But still, this is good to know.
