### ISSUE TITLE
Swap filling with mspass job

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#377]
I encountered a memory problem running a modestly large dataset with mspass on a desktop system in the all in one mode.  Omitting some details this is the parallel workflow I was running:
```
query={"source_id" : {"$exists" : True}}
srcid_list = db.wf_miniseed.distinct("source_id",query)
print("length of source_id list=",len(srcid_list))
t0=time.time()
for id in srcid_list:
    print("Starting work on ensemble with source_id=",id)
    query={"source_id" : id}
    n=db.wf_miniseed.count_documents(query)
    print("Ensemble size=",n)
    cursor=db.wf_miniseed.find(query)
    seisbag = read_distributed_data(db,cursor)
    seisbag = seisbag.map(set_tref)
    seisbag = seisbag.map(normalize,source_matcher)
    seisbag = seisbag.map(normalize,channel_matcher)
    seisbag = seisbag.map(set_Ptime_atomic,model)
    seisbag = seisbag.map(detrend,type='constant')
    seisbag = seisbag.map(cautious_ator)
    seisbag = seisbag.map(WindowData,-150.0,250.0)
    seisbag = seisbag.map(rtoa)
    #seisbag = seisbag.map(db.save_data)
    #seisbag.compute()
    seisbag = mspass_dask_foldby(seisbag,key="source_id")
    seisbag = seisbag.map(bundle_seed_data)
    result = seisbag.compute()
    # In this context it wouldn't do anything to put this in a map operator as there as 
    # it is like the highlander "there can be only one"
    db.save_ensemble_data(result[0],data_tag="serial_save")
    del result
    del seisbag
t = time.time()
print("Time to process data set=",t-t0)
print("Time per ensemble=",t-t0/len(srcid_list))
    

```
It died multiple times before i caught it while watching the ubuntu system monitor.   This version is interesting because it should recover memory at the bottom of the loop and I tried to even force this with the del commands.   While I running this script  I watched memory usage with ubuntu's system monitor.  I can observe memory use peak just before calling save_ensemble_data and del is called on result and seisbag.    There are hints of a memory leak as the baseline slowly grows as the job continues.  I don't think the leak is serious though.   Bad things started to happen when the peak memory hit 100% and you can see swap being added.  From then as each cycle the peak hits 100% memory use I saw swap grows a bit.    I watched this for one run and when swap filled and memory filled as you would expect the notebook died with a "dead kernel" error. 

I then added a temporary swap to this system.  It was previously only 10 G which for 16 G RAM was small.  I boosted that to 30 G, restarted the container, and ran it again.   As I'm composing this I see the job working up to the section where it died earlier.  The processing slowed way down when it hit the ensemble it stumbled on previously (cpu usage dropped) when RAM filled and the systems started paging.   It took about 5 times longer to get through the big memory section (I think in the script that is in the call to bundle which creates two copies inside itself of the ensemble it is bundling) but after it finished memory dropped back to where it was before.   Swap dropped this time but did not fully recover.   The test job completed fine and got past the point that was killing it earlier with a smaller swap.   RAM used dropped to background I saw for this system when the docker container was running but idle.

I next killed the notebook.  RAM used changed from 5.8 G to 1.9  and swap changed from 8.9 G to 2.3 G.   I then restarted the docker container and RAM use changed on a tiny bit to 2.5 G and swap was unchanged.   After starting MongoDB and worked to the same point in the notebook to run the script above and it increased a bit to 2.8 G and swap again was stable.   If I started it again i am pretty certain it would again work as before.   

Watching this in real time i don't really think this is a memory leak as I first feared.  I have a suspicion that the earlier behavior was made worse by not restarting the container.   Reading docker's description of memory management with docker found [here](https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details) hints that it seems likely the system state of the container was messed up after I filled memory.   

A couple things I think we need to do to followup before this issue is closed are:
1.  We need to figure out how to predict the memory use requirements of a dask/spark workflow like this.    I doubt the dask or spark document have much guidance on this issue because most of the applications you see work with atomic data much smaller than our waveform data objects.   An upper bound must be some multiplier times the number of workers times some estimate of the largest sized object in the workflow.  How can we get a handle on this?
2. I think something in this setup is not releasing swap correctly.   Note above the swap use did not change until I exited docker.   That would not be an issue for a batch job, but could be an issue while one was prototyping a bigger job like I was here.   Is this a know issue?  Any ideas for how to test this observation in a more controlled manner?
3. We definitely need to add something to our documentation on this issue.   This will bite anyone trying to handle large data sets, especially if ensembles are ever involved. Note I'm about to try a variant of the above that tries to eat the entire data set up and do the groupby operator on a full bag of the entire data set.  That died eariier and it will be interesting to see if it works now with a larger swap space.

**Comment by wangyinz** [comment]
Well, I don't know the answer to any of the questions, and maybe there isn't a good answer anyway. Essentially the use of memory should be close to the size of data consumed, and that should always be a good estimate. If the memory consumption is too much more than that, I think there is a problem in our code (or dask, mongo, or jupyter notebook). So, I guess the question here is: how much data are you processing in this workflow.

**Comment by pavlis** [comment]
Tried a variant of the workflow above and it is crashing the container by filling memory and swap.   To assure there wasn't a state problem from a previous run I restarted the container and ran this variant on a 19 event data set from the usarray (actually better called lower 48 broadband data) data from 2012:
```
model = TauPyModel(model="iasp91")
t0=time.time()
# error with undefined source_id without this query
query={"source_id" : {"$exists" : True}}
cursor = db.wf_miniseed.find(query).sort("source_id")
seisbag = read_distributed_data(db,cursor)
seisbag = seisbag.map(set_tref)
seisbag = seisbag.map(normalize,source_matcher)
seisbag = seisbag.map(normalize,channel_matcher)
seisbag = seisbag.map(set_Ptime_atomic,model)
seisbag = seisbag.map(detrend,type='constant')
seisbag = seisbag.map(cautious_ator)
seisbag = seisbag.map(WindowData,-150.0,250.0)
seisbag = seisbag.map(rtoa)
seisbag = mspass_dask_foldby(seisbag,key="source_id")
seisbag = seisbag.map(bundle_seed_data)
seisbag = seisbag.map(db.save_ensemble_data,data_tag="parallel_save")
seisbag.compute()
t=time.time()
print("Time to process data set=",t-t0)
```
Note dask does a much better job of throughput with this job as it uses 100% of all 8 cpus on this machine until it starts paging.   The job hits the memory limit and I then watch swap slowly grow until the job crashes and the notebook gives the "dead kernel" message.   As that developed the cpu usage decline slowly due, I'm 100% sure, to paging.  With this configuration it took about 12 minutes for this job to fill memory.  Strangely it stuck in a state with memory full and swap full for several minutes (around 5) before I lost patience and killed the running container.  The data set it is ingesting is just over 13 GB of miniseed data but miniseed is compressed so when uncompressed expands almost a factor of 10 to 130 G.   

Note at the conclusion of this job no date had been saved.  It seems no data in the pipeline had even reached the save_ensemble_data call.   Not good.

We really need to get to the bottom of this to understand this problem.  I think our problem is naive memory management.  There is a pretty good reference in the dask documentation [here](https://distributed.dask.org/en/stable/memory.html) but someone with better background on dask than me needs to interpret that page and verify what I'm about to say is reasonable.  That page gives a geeky but fairly clear explanation of how dask, at least, handle memory.  I'm not 100% sure but I think it explains why the first algorithm could handle these data while the second does not.  I think the second version handles the entire bag as a "futures" and from what is written there I think it means it will do just what I observed - ingest data into memory until the entire computation finishes.   In this case it can't because the data set is too huge.  By blocking the data up into ensembles the first algorithm only needs to hold copies of the ensemble it is working with.   The "futures" in that case is the data in the pipeline linked to one ensemble.  What is more ambiguous is how many copies are in the pipeline in a setting like this.   Each ensemble in this data set starts with a size around 10 GB.   It gets reduced by windowing quickly to 1/10 of that size in this job but at least two other distinct things float around (the windowed TimeSeries data and the output of bundle (SeismogramEnsemble)).   That is in the ballpark of the memory use I watched this beast use when it ran successfully with the ensemble-based version (total used was around 30 GB).   

This has some big ramifications on the way we should advise user's to structure a workflow.   I reiterate it is a really high priority to understand this problem and at least document what will and won't work for handling very large data sets that are the primary design goal of MsPASS.

**Comment by wangyinz** [comment]
Well, this is totally expected. I guess the code never run pass the `seisbag = read_distributed_data(db,cursor)` line in the second run. This step will read in the full dataset (130GB as you estimated), and it simply doesn't fit into the memory. 

Probably it is a bad idea to start with using dask.distributed on a single node of very limited memory, and that might be the advice to put in our documentation. With that said, there should be some tweaks in worker configuration and/or partition size to make the second workflow run, but those options will probably only be for knowledgeable users. Normal users should just run on a cluster of sufficient memory for the job. In this case, I think it will be somewhere of more than 130GB of memory, which is small for any modern HPC systems.

**Comment by pavlis** [comment]
I think the solution to this problem is (at least partially) found on [this page](https://distributed.dask.org/en/stable/worker-memory.html) - at least for dask.   

I don't know how we are handling this actually, but we probably need a way to change the defaults for the "--memory-limit" argument for launching a worker described on that page.   Because hardware configuration is system dependent this will probably fall on the user to change that if they hit a problem.   Once we understand this better we can hopefully improve the documentation on memory management. 

Note that page has some useful easily linked related advanced topic pages worth perusing by all developers who are past the basics.

**Comment by pavlis** [comment]
We have made progress on this issue, but it is not fixed.   Progress is now when I watch dask's monitor it will report correct memory use.  It shows the memory use bar going red saying it knows there is a problem.   That is in contrast to before the fix that we thought would close this message.  There dask just happily drifted off into oblivion without realizing a problem with memory was surfacing.  

Now the issue is that although dask seems to know it is in trouble it still fills swap.   It starts to report spilling to disk but only reports a few K bytes before it goes into a mode of slowly consuing swapspace. It will still slowly fill swap as I watch it run on the system monitor and eventually crash my desktop.   Well, not literally crash.  It eventually freezes to the point where the only solution is a brutal power cycle.  I can head that off by killing the container run before it gets that far.  I do not know what is causing this, but we need a solution before we close this issue again.  

So summary is dask does seem to properly detect it is running out of memory but is doing something wrong that still fills swap.   My current hypothesis is that dask isn't set up right to "spill" but is somehow reverting to spilling to swap.   Requires some research on some nitty gritty details of dask and/or docker.

**Comment by pavlis** [comment]
Played with a lot more and although I'm not positive what is wrong the dask logs refer me to [the following page](https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os).   

I suspect strongly that page is describing what is causing this problem - memory hoarding by the operating system in the container.   dask diagnostics report a very large unmanaged memory and we know from much other testing the problem is not memory leaks.   @wangyinz if you could look at that reference and suggest how I can set the environment variable MALLOC_TRIM_THRESHOLD_ described there it might provide a solution.   

I did a bunch of tests, by the way, with docker using various combinations of --memory with and without values for --memory-swap and/or --memory-swappiness.   Whatever docker does by default is bad news.  If I set --memory explicitly to the same value docker does by default the job at least doesn't fill swap and crash the system.  Then it goes into this more stable mode it eventually kills the worker and leaves an error message the worker log file.   We probably should figure out what default is improper for this condition that cause that behavior.   I think it must be that --memory-swap set to unlimited by default.  If so that is bad.  It may also be that it is using a value that is improperly reported through some buried system call.

**Comment by wangyinz** [comment]
According to that link, it seems all we need is setting that `MALLOC_TRIM_THRESHOLD_` before starting the worker. If so, we can just use the `-e` option. i.e.,
```
docker run -e MALLOC_TRIM_THRESHOLD_=0 THE_REST_OF_COMMANDS
```
Also, it seems that dask also supports changing the config from the client by calling the set method like: `dask.config.set({"distributed.nanny.environ.MALLOC_TRIM_THRESHOLD_": 0})`. I am not sure how well it works, but I do see people discussing it [here](https://github.com/dask/distributed/issues/3898).

**Comment by pavlis** [comment]
Tried that and it seems to have no real effect.   

I have struggled with this for many hours in the past day and am getting only confusing results.  I won't try to explain because right now I don't understand a lot of the behavior I'm seeing.   I have only guesses that are best not preserved here.   One thing that is quite clear is that an issue here is that I'm trying to have this machine eat an elephant.   I'm running an ensemble-based processing flow and the size of each ensemble is about 5 G.   With default container setup it is trying to run 8 threads that aim to process 8 ensembles simultaneously.  That translates to over 40 G of memory.   In a machine with "only" (laughable statement only a few years ago) 16 G of memory that is, I think, the root of this problem.   You can only eat an elephant one bite at a time and if you take too big of a bite you choke.  I think dask is choking.

I'm about to think we should write this off as unsolvable for now and add a section to the user's manual about memory management and reference this eating an elephant example.

**Comment by pavlis** [comment]
On a bit more reflection I think I will close this issue with one key positive point easily missed.   That is, adding the __sizeof__ method in the bindings for all standard data object did solve the most serious problem that initiated this issues page.  That is, when combined with using -e MALLOC_TRIM_THRESHOLD_=0 dask will at least not crash the system.   It seems to instead recognize memory fill conditions correctly and kill workers.   The residual problems I'm seeing are different.   It doesn't exit from the failure cleanly and seems to go through a cycle of killing workers a few times before it gives up.   On reflection I think that is sensible behavior.   

I think I will close this with two important recommendations we make sure we fix:
1.  The standard container probably should set MALLOC_TRIM_THRESHOLD_ to something instead of default.  It maybe shouldn't be zero, but that is the simplest solution.
2. We really need a memory management section in our user's manual.   There is still a lot  we don't know about these issues for dask and spark is a total unknown on the same problem.  I think we need to preserve what we know now in the manual and make it clear where people might need to be careful.

**Comment by pavlis** [comment]
Postscript to the above.   Confirm the hypothesis that my workflow was not the issue but the problem was dask couldn't eat the elephant.  I simply used a "limit(30)" qualifier when reading the ensembles to reduce size by 2 orders of magnitude.  The test job then completed with no issues.

**Comment by wangyinz** [comment]
That's great!
