### ISSUE TITLE
Error handling problem with database.index_mseed_file

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#416]
I discovered a problem with the index_mseed_file method of database.   It is not handling a common error as I think it should.   This issue is that if the method is passed a file name or a file name with a dir argument the method does not check to see if the file exists.  If the file does not exist the function called in libmseed silently returns a null result.   Such files are silently skipped with no message of any kind.   

The offending section is lines 5708-5704:
```
if dir is None:
            odir = os.getcwd()
        else:
            odir = os.path.abspath(dir)
        if dfile is None:
            dfile = self._get_dfile_uuid("mseed")
        fname = os.path.join(odir, dfile)
        (ind, elog) = _mseed_file_indexer(fname)
        ids_affected = []
        for i in ind:
            doc = self._convert_mseed_index(i)
            doc["storage_mode"] = "file"
            doc["format"] = "mseed"
            doc["dir"] = odir
            doc["dfile"] = dfile
            thisid = dbh.insert_one(doc).inserted_id
            ids_affected.append(thisid)
```
Immediately after the line `fname = os.path.join(odir, dfile)` the code should test if fname exists. 

Why I didn't just fix this is I'm not sure what action should be taken?   It might be possible with the logic of that function to use the elog mechanism to post this as an error.   I think that is not the right approach here though as it would be unusual, I think, for people to be running this task in parallel.  I think the right approach in this case is to have the code throw an exception in this case.   If we accept that model here use in a parallel workflow could still be handled but we might supply a parallel wrapper that would have an exception handler and recast the output of index_mseed_file something like this:
```
def  index_mseed_file_parallel(db,*arg, **kwargs):
   try:
      db.index_mseed_file(*arg,**kwargs)
      ret = None
   except ExceptionType(TBD):
     ret= message from exception 
   return ret
```
Result will then be an RDD/bag of either None or error message strings.   User would need to scan the RDD/bag to search for thing not None for errors.  

I'm not sure what the exception type should be as there is probably a standard python exception type for file io failure.

**Comment by wangyinz** [comment]
I think your solution of using the error message makes sense. The built-in exception type here should be `FileNotFoundError`. @Yangzhengtang could you please fix this? It should be straightforward.
