### ISSUE TITLE
ambiguous use of the keyword "delta"

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#430]
This is a bit of a trivial issue, but one putting into the record largely as a warning to users.   I just got had a confusing output from working with mspass in a workflow that used the obpsy wrapped "detrend" and did some travel time calculations to set P predicted P wave arrival times with each datum.   The problem that happened was forgetting that for obspy "delta" is a special keyword reserved for the data sample interval.   In mspass we use the internal attribute "dt" (e.g. a TimeSeries object d can fetch the sample interval as d.dt.) to define that fundamental data property.   The problem is I decided to set the field with the key "delta" as the epicentral distance from source to receiver in degrees.   Doing so caused the conversion back and forth within resample to have the sample interval wrong in the datum returned by resample.   

Now, officially I did that wrong as delta is already defined in the mspass schema as the data sample interval.  This is a classic example of namespace collisions where the same word can be used to define completely different concepts.   Still, that was too easy to do as I suspect if we took a vote with seismologists about what they would guess the keyword "delta" was used for a big majority would say epicentral distance and not data sample interval.   

There is no solution to this problem I can think of.  I suggest @wangyinz comment on my post and close this issue.   As I said I think the caveat is worth preserving.

**Comment by wangyinz** [comment]
Aha... that is a good catch I guess. Well, I think you have the point here that there is no solution, or at least no intuitive solution. Ultimately, this is a user error more or less...
