### ISSUE TITLE
problem with resample function

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#431]
Was working on our getting started tutorial.   Was adding resampling to the workflow in the tutorial and discovered we definitely have bug in that function somewhere.   This loop is showing the problem:
```
...
resampler=ScipyResampler(20.0)
decimator=ScipyDecimator(20.0)
...
for doc in cursor:
    d = db.read_data(doc,normalize=['source'])
    print("dt in=",d.dt)
    d = normalize(d,station_matcher)
    print("dt out=",d.dt)
    d = detrend(d,type="constant")
    d = resample(d,decimator,resampler)
    d = set_Ptime(d,model=ttmodel)
    # We don't need to test if d is dead here because ator 
    # is a mspass function that handles that automatically
    d = ator(d,d["Ptime"])
    d = WindowData(d,stime,etime)
```
Run on 4 inputs it gives this output:
```
dt in= 0.025
dt out= 0.025
dt in= 0.025
dt out= 0.025
dt in= 0.025
dt out= 0.025
dt in= 0.025
dt out= 0.025
```
Meaning resample did nothing.  Note the constructors for the decimator and resampler instances set the target sample rate to 20 sps and the above if 1/0.025 = 40 sps.  The dt out lines should have had 0.05.   

I do not understand how our tests could have missed this, but something is wrong.   I suspect the soft test we used for slippery clocks may be too generous.

**Comment by wangyinz** [comment]
In the code above, you have 
```
    print("dt in=",d.dt)
    d = normalize(d,station_matcher)
    print("dt out=",d.dt)
```
which is printing the dt right before and after the normalize call instead of the resample call. Is that the problem here? Other than that, I don't see any difference in your usage compared to the test there: https://github.com/mspass-team/mspass/blob/44aa03372470bd3f8a18eb6636698c247de1c0e2/python/tests/algorithms/test_resample.py#L122-L128
Not sure what else can go wrong...

**Comment by pavlis** [comment]
Well that is embarrassing.   Classic thing where you get blinded to the obvious.   I'm going to close this with a red face.
