### ISSUE TITLE
pytest code with pyspark

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#471]
In trying to solve problems with pytest code for our `distributed.py` module I ran across something we should consider implementing in all our pytest code that test pyspark.    The thing we should do is always use a fixture that sets up the spark context once and only once for a given module.  I found a number of sources talking about this point but [this one](https://engineeringfordatascience.com/posts/pyspark_unit_testing_with_pytest/) I found particularly illuminating.   The new test module `test_distributed.py` in a pending branch called "cleanup_database" should illustrate how to do this once I manage to get it working and push those changes.

**Comment by pavlis** [comment]
@wangyinz would you remind me what you told me outside this forum on how spark_context is being handled in our standard pytest runs on github?   I suggest you put that in writing and close this issue.   

I'm running into this again doing a bug fix distributed.py and when I run pytest as I think I should:
```
pytest python/tests/io/test_distributed.py 
```
I get a ton of these errors for all  the test functions in that file that aim to test spark:
```
E       fixture 'spark_context' not found
>       available fixtures: SeismogramEnsemble_generator, TimeSeriesEnsemble_generator, anyio_backend, anyio_backend_name, anyio_backend_options, atomic_seismogram_generator, atomic_time_series_generator, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, define_kill_one, define_kill_one_member, define_massacre, define_set_dir_dfile_atomic, define_set_dir_dfile_ensmble, define_set_one_invalid, define_set_one_invalid_member, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, setup_environment, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```
I have a vague memory that something in the github setup runs a fixture that sets the variable "sc" magically to a stock spark_context datum.  I can't fix this bug until this is resolved as the local test just errors out before even getting to the revision I need to verify.

**Comment by wangyinz** [comment]
I don't quite remember this, but I believe such error is due to the lack of the `pytest-spark` package. After pip installing this, pytest will automatically create the fixtures for spark.
