### ISSUE TITLE
bug in merge

### ISSUE THREAD

**Issue by pavlis** [mspass-team/mspass#520]
I am pretty sure I just found an off by one error bug in our merge function for handling continuous data.   Working on processing very long time series data from Homestake where the merge window was of the order of 3 months long.  The window happened to cross the 2015-2016 new year where all the input files have an break.   36 channels of data after merging all have a 1 sample gap at the year boundary.   

This is almost certainly an off by one error in the C++ code that does the heavy lifting for this function.  It is my problem to fix it, but I wanted to put this here for the record.

**Comment by pavlis** [comment]
I am becoming skeptical this problem is caused by merge.  I am suspecting we may have an issue with our miniseed implementation.   I'm seeming some very inconsistent data.  A critical reason to be sure the problem is our implementation is that the gap I'm seeing at the year boundary in the data read by MsPASS does NOT appear in data indexed with Antelope's equivalent `miniseed2db`.  i.e. I can run their graphical display ("dbpick") at the year boundary are the data are continuous.   

There is definitely an issue with the index we produce with index miniseed.   The index for one channel has only two documents.  Here is the output I see that shows the issue:
```
for doc in cursor:
    print(UTCDateTime(doc['starttime']),UTCDateTime(doc['endtime']))

2015-03-25T16:36:24.000004Z 2015-12-31T23:45:44.000004Z
2016-01-01T00:01:12.000000Z 2016-11-30T07:47:33.000000Z
```
Notice there is about a 15 minute gap between the endtime of the first and the starttime of the second.   Weirder is obspy's reader, which we use to read the actual data files, gives a different answer.   Here is the output of different combinations of things produced by reading the data linked to the first document above.
```
d1=db.read_data(doc,collection='wf_miniseed')

print(UTCDateTime(d1.endtime()))
2015-12-31T23:06:46.000004Z

print(UTCDateTime(d1['endtime']))
2015-12-31T23:45:44.000004Z

print(UTCDateTime(d1['last_packet_time']))
2015-12-31T23:06:47.000000Z
```
The important thing is the that the output of the endtime method is different from the time defined by the "endtime" Metadata attribute by several minutes.   

So, the problem seems to actually be in the miniseed data.  The inconsistency of the obspy reader result and the time computed by the indexer are going to be particularly difficult to resolve.   I'll start with our indexer on these files to see if I can figure out what it is doing wrong,.

**Comment by pavlis** [comment]
Good news and bad news about this issue after digging deeper.   The good news is the problem is mostly harmless.  The bad news is that when it isn't harmless it is very bad and creates timing errors.  

I'm not finished with this, but after the previous comment and reviewing our implementation I realized the problem was most likely in the miniseed indexing and reading and not the `merge` function as I first thought.   My hypothesis immediately above, however, was not the specific problem that caused me to post this originally, but part of generic problem:   dirty miniseed from a direct dump from digitizers can have all kinds of nasty problems.   I encountered this problem from dealing with almost raw data from the Homestake experiment.  Poking around shows me there are  a lot of issues with the data itself than above.  Listing them is not the point.  The point is our previous implementation had two problems that did not make it as robust as it should be:
1.  The previous version of the C++ function called `mseed_file_indexer` was not handling time tears correctly in some situations.  A lot of that can be blamed on an ugly way I had done the logic for the main, data-driven, loop.   You can look at the current version and quickly see what I mean.   I cleaned that up and the confusing behavior got less confusing.
2. The more fundamental problem is a disconnect with the obspy miniseed reader.  In the current implementation we use obspy's reader driven by the index we produce with  the indexing method of Database.   What was happening because of the "not robust" issues with the index created by `mseed_file_indexer` was the obspy reader was handling the data problems in the miniseed file differently from `mseed_file_indexer`.   To make matters worse the private method  `Database._read_data_from_dfile` was assuming the database value for starttime was correct.  That assumption turned out to not always be correct causing timing errors in some situations.

So, this is a serious problem with ugly miniseed files but is probably rarely if ever an issue with clean data from an FDSN data center.  I'll keep chipping away at this revision and hope to get a fix within the next week.  We need to go over some details at our next developer meeting.

**Comment by wangyinz** [comment]
aha... that's good to know! I guess we just need to follow how obspy handles the problem data in our indexer then?
